name: Quarto Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: your-dockerhub-username/quarto-render:latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory /__w/$(basename $GITHUB_REPOSITORY)/$(basename $GITHUB_REPOSITORY)

      - name: Initialize gh-pages branch if needed
        run: |
          if ! git ls-remote --heads origin gh-pages | grep -q gh-pages; then
            echo "Creating gh-pages branch..."
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initialize gh-pages branch"
            git push origin gh-pages
            git checkout main
          else
            echo "gh-pages branch already exists"
          fi

      - name: Collect and Install Python dependencies
        run: python3 /usr/local/bin/collect_python_deps.py

      - name: Collect and Install R packages
        run: Rscript /usr/local/bin/collect_r_deps.R

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v@v2.1.9
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
